# Generated by Django 4.0.1 on 2022-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='cite',
            field=models.CharField(blank=True, max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='телефон'),
        ),
    ]
